"use client";

import Script from "next/script";

import { useState, useEffect } from "react";

import Header from "./layout/header-layout";
import Footer from "./layout/footer-layout";

import { ibm, ps2p } from "./fonts";

import "./layout/header-layout/header.scss";
import "@/scss/globals.scss";
import "@/scss/button.scss";

/* 
export const metadata = {
    title: "BDAO",
    description: "Generated by create next app",
}; 
*/

// export const metadata = {
//     title: "BDAO",
//     description: "Generated by create next app",
// };

function LoadingPage() {
    return (
        <div className="main-bg h-[1000px] flex flex-col justify-center items-center">
            <model-viewer
                        src="/media/models/B-logo.glb"
                        loading="eager"
                        auto-rotate
                        camera-controls
                        rotation-per-second="30deg"
                        touch-action="pan-y"
                        disable-zoom
                        exposure="0.6"
                        style={{
                            width: "75px",
                        }}
            ></model-viewer>
            <p className="fmb text-sm">Loading Website ...</p>
        </div>
    );
}

export default function RootLayout({ children }) {
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        setTimeout(() => {
            setLoading(false);
        }, 4000);
    }, []);

    return (
        <html lang="en">
            <head>
                <Script
                    src="https://ajax.googleapis.com/ajax/libs/model-viewer/3.0.1/model-viewer.min.js"
                    type="module"
                />
                {/* <link rel="icon" href="/favicon.ico" /> */}
                {/* <link rel="stylesheet" href="/font.scss" /> */}
            </head>

            <body className={`${ibm.variable} ${ps2p.variable}`}>
                {loading ? (
                    <LoadingPage />
                ) : (
                    <>
                        <Header />
                        <div className="main-bg">
                            <div className="">
                                <section className="pt-[81px]"></section>
                                {children}
                            </div>
                        </div>
                        <Footer />
                    </>
                )}
            </body>
        </html>
    );
}
